### ISSUE TITLE
About invalid status in SwitchResX

### ISSUE THREAD

**Issue by shure22** [comsysto/Display-Override-PropertyList-File-Parser-and-Generator-with-HiDPI-Support-For-Scaled-Resolutions#2]
Hi,

This tool is amazing and really helped me a lot. However, I was stuck at the last step, or say I didn't get what should be after doing the steps. I tried many times but could not resolve it.

In SwitchResX, under the custom resolutions, the status of my custom items are just like this, System - only, invalid. I strictly followed the instructions and repeated many times, but could not figure out what's the problem.
Mac Pro 3,1
ATI Radeon HD 5770

**Comment by clouless** [comment]
Hi @shure22 thanks :)

Yeah the tool helped me a lot too to make my Dell U2515H work.
Unfortunately I cannot give too much tech support myself since all this mac "magic" is not too much my thing. What I can say about what you describe is, that it really depends on the monitor and the macOS version. macOS Sierra seems to have problems with HIDPI resolutions. El Capitan has this system-lock-thingy so that you cannot change systemfiles. And Yosemite was the last "good" and working OS (personal opinion).

So my expertise ends at that and if you need more help post your exact monitor vendor and productname together with your plist in the awesome
[tonymacx86.com forum](http://www.tonymacx86.com/threads/adding-using-hidpi-custom-resolutions.133254/) and I am sure someone can help you :)
